from copy import deepcopy
from typing import Dict, List, Protocol

from itinerary_engine.schema.models import POI


class POICatalogAdapter(Protocol):
    def search(self, destination: str) -> List[POI]:
        ...


def _poi(**kwargs: object) -> POI:
    return POI(**kwargs)


CATALOG: Dict[str, List[POI]] = {
    "tokyo": [
        _poi(
            poi_id="tokyo_sensoji",
            name="Senso-ji",
            city="Tokyo",
            category="landmark",
            district="Asakusa",
            tags=["culture", "historic", "photography"],
            estimated_cost=8,
            visit_duration_hours=1.5,
            best_time="morning",
            summary="Historic temple area with strong first-visit appeal.",
        ),
        _poi(
            poi_id="tokyo_tsukiji",
            name="Tsukiji Outer Market",
            city="Tokyo",
            category="food",
            district="Tsukiji",
            tags=["food", "market", "street-food"],
            estimated_cost=24,
            visit_duration_hours=2.0,
            best_time="morning",
            summary="High-density food stop with strong breakfast value.",
        ),
        _poi(
            poi_id="tokyo_ueno_park",
            name="Ueno Park",
            city="Tokyo",
            category="park",
            district="Ueno",
            tags=["nature", "culture", "walk"],
            estimated_cost=0,
            visit_duration_hours=1.5,
            best_time="afternoon",
            summary="Flexible outdoor stop that reduces itinerary density.",
        ),
        _poi(
            poi_id="tokyo_teamlab",
            name="teamLab Planets",
            city="Tokyo",
            category="activity",
            district="Toyosu",
            tags=["art", "immersive", "indoor"],
            estimated_cost=28,
            visit_duration_hours=2.0,
            best_time="afternoon",
            indoor=True,
            summary="Immersive digital art experience.",
        ),
        _poi(
            poi_id="tokyo_shibuya_sky",
            name="Shibuya Sky",
            city="Tokyo",
            category="landmark",
            district="Shibuya",
            tags=["view", "photography", "city"],
            estimated_cost=18,
            visit_duration_hours=1.0,
            best_time="evening",
            summary="Observation deck with strong sunset potential.",
        ),
        _poi(
            poi_id="tokyo_harajuku",
            name="Harajuku",
            city="Tokyo",
            category="shopping",
            district="Harajuku",
            tags=["shopping", "street", "youth-culture"],
            estimated_cost=30,
            visit_duration_hours=2.0,
            best_time="afternoon",
            summary="Street shopping and trend discovery area.",
        ),
        _poi(
            poi_id="tokyo_national_museum",
            name="Tokyo National Museum",
            city="Tokyo",
            category="museum",
            district="Ueno",
            tags=["culture", "museum", "history"],
            estimated_cost=12,
            visit_duration_hours=2.0,
            best_time="afternoon",
            indoor=True,
            summary="Strong museum option for culture-heavy trips.",
        ),
    ],
    "kyoto": [
        _poi(
            poi_id="kyoto_fushimi_inari",
            name="Fushimi Inari Taisha",
            city="Kyoto",
            category="landmark",
            district="Fushimi",
            tags=["culture", "historic", "walk"],
            estimated_cost=0,
            visit_duration_hours=2.0,
            best_time="morning",
            summary="Iconic shrine complex suited for early starts.",
        ),
        _poi(
            poi_id="kyoto_nishiki_market",
            name="Nishiki Market",
            city="Kyoto",
            category="food",
            district="Downtown",
            tags=["food", "market", "local"],
            estimated_cost=20,
            visit_duration_hours=1.5,
            best_time="afternoon",
            summary="Compact food stop with local specialties.",
        ),
        _poi(
            poi_id="kyoto_kiyomizu",
            name="Kiyomizu-dera",
            city="Kyoto",
            category="landmark",
            district="Higashiyama",
            tags=["culture", "view", "historic"],
            estimated_cost=10,
            visit_duration_hours=1.5,
            best_time="morning",
            summary="High-signal temple visit with broad appeal.",
        ),
        _poi(
            poi_id="kyoto_gion",
            name="Gion",
            city="Kyoto",
            category="neighborhood",
            district="Gion",
            tags=["culture", "walk", "historic"],
            estimated_cost=12,
            visit_duration_hours=1.5,
            best_time="evening",
            summary="Evening walking district with strong atmosphere.",
        ),
        _poi(
            poi_id="kyoto_arashiyama",
            name="Arashiyama Bamboo Grove",
            city="Kyoto",
            category="park",
            district="Arashiyama",
            tags=["nature", "photography", "walk"],
            estimated_cost=0,
            visit_duration_hours=2.0,
            best_time="morning",
            summary="Outdoor landmark that pairs well with a slower day.",
        ),
        _poi(
            poi_id="kyoto_railway",
            name="Kyoto Railway Museum",
            city="Kyoto",
            category="museum",
            district="Shimogyo",
            tags=["museum", "family", "indoor"],
            estimated_cost=15,
            visit_duration_hours=2.0,
            best_time="afternoon",
            indoor=True,
            summary="Family-friendly museum with high indoor utility.",
        ),
    ],
    "shanghai": [
        _poi(
            poi_id="shanghai_bund",
            name="The Bund",
            city="Shanghai",
            category="landmark",
            district="Huangpu",
            tags=["view", "city", "walk"],
            estimated_cost=0,
            visit_duration_hours=1.5,
            best_time="evening",
            summary="Iconic skyline walk and low-cost anchor stop.",
        ),
        _poi(
            poi_id="shanghai_yuyuan",
            name="Yu Garden",
            city="Shanghai",
            category="landmark",
            district="Huangpu",
            tags=["culture", "historic", "garden"],
            estimated_cost=9,
            visit_duration_hours=1.5,
            best_time="morning",
            summary="Classic heritage stop in central Shanghai.",
        ),
        _poi(
            poi_id="shanghai_museum",
            name="Shanghai Museum",
            city="Shanghai",
            category="museum",
            district="Huangpu",
            tags=["museum", "culture", "history"],
            estimated_cost=0,
            visit_duration_hours=2.0,
            best_time="afternoon",
            indoor=True,
            summary="High-value museum stop with strong cultural coverage.",
        ),
        _poi(
            poi_id="shanghai_xintiandi",
            name="Xintiandi",
            city="Shanghai",
            category="neighborhood",
            district="Huangpu",
            tags=["food", "shopping", "nightlife"],
            estimated_cost=28,
            visit_duration_hours=2.0,
            best_time="evening",
            summary="Food and lifestyle district suited for dinner hours.",
        ),
        _poi(
            poi_id="shanghai_jingan",
            name="Jing'an Temple",
            city="Shanghai",
            category="landmark",
            district="Jing'an",
            tags=["culture", "historic", "city"],
            estimated_cost=7,
            visit_duration_hours=1.0,
            best_time="afternoon",
            summary="Compact spiritual landmark in a central district.",
        ),
        _poi(
            poi_id="shanghai_tianzifang",
            name="Tianzifang",
            city="Shanghai",
            category="shopping",
            district="Huangpu",
            tags=["shopping", "arts", "walk"],
            estimated_cost=18,
            visit_duration_hours=1.5,
            best_time="afternoon",
            summary="Lane-based shopping and arts neighborhood.",
        ),
    ],
}

ALIASES = {
    "tokyo": "tokyo",
    "东京": "tokyo",
    "kyoto": "kyoto",
    "京都": "kyoto",
    "shanghai": "shanghai",
    "上海": "shanghai",
}


class StaticCatalogAdapter:
    def search(self, destination: str) -> List[POI]:
        normalized = ALIASES.get(destination.strip().lower(), destination.strip().lower())
        return deepcopy(CATALOG.get(normalized, []))
